# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-09 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='成员姓名')),
                ('gender', models.CharField(max_length=5, verbose_name='成员性别')),
                ('age', models.SmallIntegerField(verbose_name='成员年龄')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('phone', models.CharField(max_length=15, verbose_name='联系方式')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('introduce', models.TextField(verbose_name='成员介绍')),
            ],
            options={
                'db_table': 'company_member',
                'verbose_name': '公司成员',
                'verbose_name_plural': '公司成员',
            },
        ),
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='客户姓名')),
                ('contact', models.CharField(max_length=30, verbose_name='联系方式')),
                ('company', models.CharField(max_length=20, verbose_name='公司名称')),
                ('business_introduce', models.TextField(verbose_name='业务介绍')),
                ('remark', models.TextField(verbose_name='备注')),
                ('receptionist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.company_member')),
            ],
            options={
                'db_table': 'customer_info',
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='factory_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='工厂姓名')),
                ('contact', models.CharField(max_length=30, verbose_name='联系方式')),
                ('company', models.CharField(max_length=20, verbose_name='公司名称')),
                ('business_introduce', models.TextField(verbose_name='业务介绍')),
                ('remark', models.TextField(verbose_name='备注')),
                ('receptionist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.company_member')),
            ],
            options={
                'db_table': 'factory_info',
                'verbose_name': '工厂信息',
                'verbose_name_plural': '工厂信息',
            },
        ),
        migrations.CreateModel(
            name='supplier_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='供应商姓名')),
                ('contact', models.CharField(max_length=30, verbose_name='联系方式')),
                ('company', models.CharField(max_length=20, verbose_name='公司名称')),
                ('business_introduce', models.TextField(verbose_name='业务介绍')),
                ('remark', models.TextField(verbose_name='备注')),
                ('receptionist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.company_member')),
            ],
            options={
                'db_table': 'supplier_info',
                'verbose_name': '供应商信息',
                'verbose_name_plural': '供应商信息',
            },
        ),
    ]
